"""create tb_vendor, tb_product

Revision ID: 1e8b97fcbf9b
Revises: 
Create Date: 2021-09-23 15:04:28.347904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8b97fcbf9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_vendor',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CNPJ', sa.String(), nullable=False),
    sa.Column('City', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('CNPJ')
    )
    op.create_table('tb_product',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Code', sa.String(), nullable=False),
    sa.Column('Price', sa.Numeric(scale=2), nullable=True),
    sa.Column('Vendor_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Vendor_Id'], ['tb_vendor.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Code')
    )
    op.create_index(op.f('ix_tb_product_Vendor_Id'), 'tb_product', ['Vendor_Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_product_Vendor_Id'), table_name='tb_product')
    op.drop_table('tb_product')
    op.drop_table('tb_vendor')
    # ### end Alembic commands ###
